language: csharp
solution: T3000Controls.sln
script:
  - cd SliderControlLibrary.Tests
  - nuget restore
  - xbuild /p:Configuration=Release
  - cd ..
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./SliderControlLibrary.Tests/bin/Release/SliderControlLibrary.Tests.dll
