version: 0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore ".\T3000Controls.sln"
build:
  project: .\T3000Controls.sln
test_script:
  - nunit3-console.exe ./T3000Controls.Tests/bin/Release/T3000Controls.Tests.dll
